name: Build and deploy website
on:
  push:
    branches:
      - main # if any push happens on branch `master`, run this workflow. You could also add `paths` to detect changes in specific folder

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      VITE_GOOGLE_MAPS_API_KEY: ${{ vars.VITE_GOOGLE_MAPS_API_KEY }}
      VITE_STRIPE_PUBLISHING_KEY: ${{ vars.VITE_STRIPE_PUBLISHING_KEY }}
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
      - name: Install
        run:
          npm install
      - name: Build 🔧
        run:
          npm run build
        working-directory: ./packages/website
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: ./packages/website/dist # output folder from `npm run build:website`
