name: Test project files on push

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
            node-version-file: '.node-version'
            cache: 'npm'
      - name: Installing node_modules
        run: npm ci
      - name: Build the app
        run: npm run build
  test:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
            node-version-file: '.node-version'
            cache: 'npm'
      - uses: cachix/install-nix-action@v26
        with:
          extra_nix_config: |
            keep-derivations = true
            keep-outputs = true
      - name: Installing node_modules
        run: npm ci
      - name: Test the app
        # use nix develop to ensure caddy is installed
        run: nix develop --command npm run test
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
            node-version-file: '.node-version'
            cache: 'npm'
      - name: Installing node_modules
        run: npm ci
      - name: Run lint
        run: npm run lint:check

  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
            node-version-file: '.node-version'
            cache: 'npm'
      - name: Installing node_modules
        run: npm ci
      - name: Run tsc
        run: npm run tsc
